<a href="https://colab.research.google.com/github/Prabhjot05112006/Assignment_6.ipynb/blob/main/Assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import Numpy

In [13]:
import numpy as np

Creating a 1D Array

In [14]:
arr1 = np.array([10, 20, 30, 40, 50])

print("1D Array:", arr1)
print("Number of dimensions:", arr1.ndim)
print("Data type:", arr1.dtype)

1D Array: [10 20 30 40 50]
Number of dimensions: 1
Data type: int64


Creating a 2D Array

In [15]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("2D Array:")
print(arr2)

print("Dimensions:", arr2.ndim)
print("Shape:", arr2.shape)
print("Data type:", arr2.dtype)

2D Array:
[[1 2 3]
 [4 5 6]]
Dimensions: 2
Shape: (2, 3)
Data type: int64


Creating a 3D Array

In [16]:
arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("3D Array:")
print(arr3)

print("Dimensions:", arr3.ndim)
print("Shape:", arr3.shape)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions: 3
Shape: (2, 2, 2)


Indexing

In [17]:
numbers = np.array([10, 20, 30, 40, 50])

print("First element:", numbers[0])
print("Third element:", numbers[2])
print("Last element:", numbers[-1])

First element: 10
Third element: 30
Last element: 50


In [18]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Element at row 1, column 2:", matrix[0, 1])
print("Element at row 2, column 3:", matrix[1, 2])

Element at row 1, column 2: 20
Element at row 2, column 3: 60


Slicing

In [19]:
numbers = np.array([10, 20, 30, 40, 50])

print("First three elements:", numbers[:3])
print("Elements from index 2:", numbers[2:])
print("Middle elements:", numbers[1:4])

First three elements: [10 20 30]
Elements from index 2: [30 40 50]
Middle elements: [20 30 40]


In [20]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("First two rows:")
print(matrix[:2])

print("First two columns:")
print(matrix[:, :2])

First two rows:
[[1 2 3]
 [4 5 6]]
First two columns:
[[1 2]
 [4 5]
 [7 8]]


Reshaping an Array

In [21]:
numbers = np.arange(1, 13)

print("Original array:")
print(numbers)

new_array = numbers.reshape(3, 4)

print("After reshaping:")
print(new_array)

Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
After reshaping:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Zeros()

In [22]:
zero_array = np.zeros((2, 3))

print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]]


Ones()

In [23]:
one_array = np.ones((3, 2))

print(one_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


arange()

In [24]:
numbers = np.arange(0, 20, 2)

print(numbers)

[ 0  2  4  6  8 10 12 14 16 18]


linspace()

In [25]:
values = np.linspace(0, 10, 6)

print(values)

[ 0.  2.  4.  6.  8. 10.]


Mathematical Operations

In [26]:
a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [12 24 35 48]
Subtraction: [ 8 16 25 32]
Multiplication: [ 20  80 150 320]
Division: [5. 5. 6. 5.]


Operations with a Single Number

In [27]:
marks = np.array([50, 60, 70, 80])

print("Original marks:", marks)
print("After adding 5:", marks + 5)
print("After multiplying by 2:", marks * 2)

Original marks: [50 60 70 80]
After adding 5: [55 65 75 85]
After multiplying by 2: [100 120 140 160]


Boolean Masking

In [28]:
marks = np.array([35, 48, 67, 72, 29, 85])

passed = marks >= 40

print("Boolean result:", passed)
print("Passing marks:", marks[passed])

Boolean result: [False  True  True  True False  True]
Passing marks: [48 67 72 85]


Broadcasting

In [29]:
prices = np.array([100, 200, 300, 400])

tax = 10

new_prices = prices + tax

print("Original prices:", prices)
print("Prices after adding tax:", new_prices)

Original prices: [100 200 300 400]
Prices after adding tax: [110 210 310 410]


Aggregate Functions.

In [30]:
marks = np.array([45, 67, 82, 55, 91, 73])

print("Sum:", np.sum(marks))
print("Mean:", np.mean(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))
print("Median:", np.median(marks))

Sum: 413
Mean: 68.83333333333333
Minimum: 45
Maximum: 91
Median: 70.0


Aggregate function with 2D Array

In [31]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Total:", np.sum(data))
print("Mean:", np.mean(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Median:", np.median(data))

Total: 450
Mean: 50.0
Minimum: 10
Maximum: 90
Median: 50.0


Small Practical Example

In [32]:
student_marks = np.array([65, 72, 48, 89, 55, 76, 91])

print("Student marks:", student_marks)

print("Average marks:", np.mean(student_marks))
print("Highest marks:", np.max(student_marks))
print("Lowest marks:", np.min(student_marks))

print("Students scoring above 70:")
print(student_marks[student_marks > 70])

Student marks: [65 72 48 89 55 76 91]
Average marks: 70.85714285714286
Highest marks: 91
Lowest marks: 48
Students scoring above 70:
[72 89 76 91]
